apiVersion: v1
kind: Service
metadata:
  name: bank-service
  namespace: pipeline-demo
  labels:
    app.kubernetes.io/part-of: bank-app
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8990
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
  selector:
    app: bank-service
    deployment: bank-service
  sessionAffinity: None
  type: ClusterIP
